name: delv_app
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  flutter_rating_bar: ^4.0.0
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8
  flutter_inner_shadow: 0.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter:

 
  uses-material-design: true


  assets:
    - assets/
    - assets/profil.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/4.png"
  image_path_android: "assets/4.png"
 

